Develop a mutual coupling model for isotropic radiators

(a) Write a code to find the element pattern overlap matrix for an array of isotropic radiators using the analytical result in the text.

To calculate the overlap matrix $A$ we use the sinc function and the distances between each of the elements within the array.

Distance between elements
$$ r = nd $$
$$ r_{mn} = r_m-r_n $$

The overlap matrix is given as:
$$ A=P_{rad}\frac{\sin(kr_{mn})}{kr_{mn}} $$

In [31]:
import numpy as np
import matplotlib.pyplot as plt

# Define antenna the parameters
f=1e9           # frequency in Hz
c=3e8           # speed of light in m/s
lam=c/f         # wavelength in m
k = 2*np.pi/lam # wave number

# Define the array
d=lam/2                 # distance between elements
rx = [0, d, 2*d, 3*d]   # rx is a 1D array with N elements
N = 4                   # Number of nodes
A = np.zeros([N, N])    # A is a 2D array with Nel rows and N columns

# sinc calculation
for m in range(0, N):
    for n in range(0, N):
        r = abs(rx[m] - rx[n])
        A[m, n] = np.sinc(k*r)

# print the overlap matrix
print("Overlap Matrix\n", A)

Overlap Matrix
 [[ 1.         -0.04359863  0.03935584 -0.03283505]
 [-0.04359863  1.         -0.04359863  0.03935584]
 [ 0.03935584 -0.04359863  1.         -0.04359863]
 [-0.03283505  0.03935584 -0.04359863  1.        ]]


(b) Use the relationship between the overlap matrix and the mutual impedance matrix to estimate the array mutual impedance matrix. Scale the impedance matrix so that the diagonal elements are equal to 50Ω.

The relationship between the array factor and the mutual impedance is:

$$ R_{rad}=\frac{2}{|I_0|^2}A $$

In [32]:
# Relationship between the array factor and the mutual impedance
Io = 1                  # Current
Za = 2*A/(abs(Io)**2)   # Impedance
Za = 25*Za              # Scaling

# print
print("Impedance Matrix\n", Za)

Impedance Matrix
 [[50.         -2.17993143  1.96779219 -1.64175247]
 [-2.17993143 50.         -2.17993143  1.96779219]
 [ 1.96779219 -2.17993143 50.         -2.17993143]
 [-1.64175247  1.96779219 -2.17993143 50.        ]]


(c) Give the impedance matrix for a four element ULA of isotropic radiators with 0.3λ spacing.

In [33]:
# Define the array
d=0.3*lam               # distance between elements
rx = [0, d, 2*d, 3*d]   # rx is a 1D array with N elements
N = 4                   # Number of nodes
A = np.zeros([N, N])    # A is a 2D array with Nel rows and N columns

# sinc calculation
for m in range(0, N):
    for n in range(0, N):
        r = abs(rx[m] - rx[n])
        A[m, n] = np.sinc(k*r)

# print the overlap matrix
print("Overlap Matrix\n", A)

# Relationship between the array factor and the mutual impedance
Io = 1                  # Current
Za = 2*A/(abs(Io)**2)   # Impedance
Za = 25*Za              # Scaling

# print
print("\nImpedance Matrix\n", Za)

Overlap Matrix
 [[ 1.         -0.05971285 -0.05585509 -0.04975779]
 [-0.05971285  1.         -0.05971285 -0.05585509]
 [-0.05585509 -0.05971285  1.         -0.05971285]
 [-0.04975779 -0.05585509 -0.05971285  1.        ]]

Impedance Matrix
 [[50.         -2.98564268 -2.79275436 -2.48788931]
 [-2.98564268 50.         -2.98564268 -2.79275436]
 [-2.79275436 -2.98564268 50.         -2.98564268]
 [-2.48788931 -2.79275436 -2.98564268 50.        ]]
