Develop a mutual coupling model for isotropic radiators
 (a) Write a code to find the element pattern overlap matrix for an array of isotropic radiators using the analytical result in the text.

In [8]:
import numpy as np
import matplotlib.pyplot as plt

N = 4                           # Number of nodes
Nel = N+1                       # Number of elements
rx = np.arange(1, Nel, 1)         # rx is a 1D array with N-1 elements
A = np.zeros([N, Nel])          # A is a 2D array with Nel rows and N columns

for m in range(0, N-1):
    for n in range(0, Nel-1):
        A[m, n] = abs(rx[m] - rx[n])

print(A)

[[0. 1. 2. 3. 0.]
 [1. 0. 1. 2. 0.]
 [2. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]


 (b) Use the relationship between the overlap matrix and the mutual impedance matrix to estimate the array mutual impedance matrix. Scale the impedance matrix so that the diagonal elements are equal to 50Ω.